[package]
name = "cargo_cli_bin_embed"
version = "0.1.0"
edition = "2021"

[dependencies]
pact_verifier_cli = {version = "1.1.4", path = "/Users/saf/dev/pact-foundation/pact-reference/rust/pact_verifier_cli"}
